config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/minor"

  root to: 'home#index'

  get "departments/:id/line_graph_data", to: "departments#line_graph_data"
  get "departments/:id/:display_name", to: 'departments#show'
  get "departments", to: 'departments#index'
  
  get "leaderboards", to: "leaderboards#index"

  get "contracts/find", to: "contracts#find"
  get "contracts/search", to: "contracts#search"

  get "charts", to: "charts#show"
end

app/controllers/home_controller.rb
require 'Summary'

class HomeController < ApplicationController
  def index
    @summary = Summary.new
    @epp_spending_leaders = Department.unscoped.order(epp_percent_cache: :desc).limit(5)
  end

  def minor
  end

  def coming_soon
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/coming_soon.html.erb
Hello

app/views/home/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <h1>Welcome to <span style="color: #1ab394 !important;"><strong>GreenBuyer</strong></span>!</h1>
                <ol class="breadcrumb">
                    <li>
                        <p>GreenBuyer links state department purchase order data with “Environmentally Preferable Purchasing” (EPP) contract data, providing transparent data for managers and the public on state department purchasing, and helping staff improve on their department’s performance and meet EPP purchasing goals.</p>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>    

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="container">

        <div class="row">
            <div class="col-md-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h3>EPP Spending Percent (%) By Year</h3>
                    </div>
                    <div class="ibox-content">
                        <div id="spending-line-chart"></div>
                    </div>
                    <div class="ibox-footer">
                        <br>
                        <h2></h2>
                    </div>

                </div>
            </div>

            <div class="col-md-6">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-1" aria-expanded="true">All</a></li>
                        <% for i in 2012..Date.today.year %>
                            <li class=""><a data-toggle="tab" href=<%= "#tab-#{i}" %> aria-expanded="false"><%= i %></a></li>                                             
                        <% end %>                        
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane active">
                            <div class="panel-body">
                                <div id="total-donut-chart" data-chart-year="ALL" class="donut-chart" ></div>
                                <h2 style="text-align: center;"><strong>Total: </strong><%= number_to_currency @summary.total_spending %></h2>
                            </div>
                        </div>
                        <% for i in 2012..Date.today.year %>
                            <div id=<%= "tab-#{i}" %> class="tab-pane">
                                <div class="panel-body">
                                    <div id=<%= "total-donut-chart-#{i}" %> data-chart-year="<%= i %>" class="donut-chart"></div>
                                    <h2 style="text-align: center;"><strong>Total: </strong><%= number_to_currency @summary.total_spending_by_year(i) %></h2>
                                </div>
                            </div>                        
                        <% end %>
                    </div>
                </div>
            </div>
        </div>       
        <br>     
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>EPP Spending by Percent (%) Leaders </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>                  
                    <div class="ibox-content">
                        <table class="footable table table-striped" data-filter="#filter" data-page-size="5">
                            <thead>
                                <tr>
                                  <th>#</th>
                                  <th>Department</th>
                                  <th>%</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @i = 1 %>
                              <% @epp_spending_leaders.each do |leader| %>
                                <tr>
                                  <td><%= @i %></td>
                                  <td><a href=<%= department_path leader %>><%= leader.display_name %></a></td>
                                  <td><%= number_to_percentage leader.epp_percent %></td>
                                </tr>
                                <% @i = @i + 1 %>
                              <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="ibox-footer text-right">
                        <a href="/leaderboards">Full Leaderboard ➝</a>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</div>

<%content_for :javascript do %>
    <script type="text/javascript">

    $(function() {
        var chartStore = {};

        var handleDonutChart = function(tabId) {

            var donutContainer = $(tabId).find(".donut-chart");
            if (typeof chartStore[tabId] === "undefined") {

                $.get("/charts", 
                    {
                        entity_type: "summary", 
                        chart_type: "donut", 
                        chart_year: donutContainer.attr('data-chart-year')
                    }, 
                    function(data){

                        chartStore[tabId] = Morris.Donut({
                            element: donutContainer,
                            data: data,
                            resize: true,
                            colors: ['#990000', '#1ab394', '#CC8080'],
                            formatter: function(y, data) {
                                return accounting.formatMoney(y);
                            }
                        });   
                    }
                );
            } else {
                chartStore[tabId].redraw();
            }   
        }

        $.get("/charts", 
            {entity_type: "summary", chart_type: "line"}, 
            function(data){

                var graphData = [];
                data.forEach(function(record) {
                    graphData.push({
                        year: record.year.toString(),
                        value: Math.floor(record.value * 100) / 100
                    });
                });

                Morris.Line({
                    element: 'spending-line-chart',
                    data: graphData,
                    xkey: 'year',
                    ykeys: ['value'],
                    resize: true,
                    lineWidth: 4,
                    labels: ['Value'],
                    lineColors: ['#1ab394'],
                    pointSize: 5,
                    xLabels: "year",
                    yLabelFormat: function(y) {
                        return y.toString() + "%"
                    }
                });

                $("#spending-line-chart").find("circle").css("cursor", "pointer").on("click", function(e){ 
                    var xVal = $(this).attr("cx");
                    year = $("#spending-line-chart").find("text[x='"+ xVal +"']").find("tspan").html(); 
                    $("a[href='#tab-"+year+"']").click();
                });                
            }
        );

        $(document).on('shown.bs.tab', function (e) {
            var tabId = $(e.target).attr('href');
            handleDonutChart(tabId);
        });

        handleDonutChart("#tab-1");
        $('#purchase-table').footable();

    });
    </script> 
<%end %>

app/views/home/minor.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Simple example of second view
                </h1>
                <small>Configure in home_controller.rb as minor view.</small>
            </div>
        </div>
    </div>
</div>